type AchievementRoleName = 'system_admin' | 'worker' | 'resource_manager' | 'travel_coordinator';

export type AchievementSeedDefinition = {
  name: string;
  description: string;
  icon_url: string;
  trigger_rule: string;
  roleNames: AchievementRoleName[];
};

const icon = (slug: string) =>
  `https://placehold.co/128x128/0f172a/f8fafc?text=${encodeURIComponent(slug)}`;

export const achievementSeedDefinitions: AchievementSeedDefinition[] = [
  {
    name: 'Login Novice',
    description: 'Unlock your first session in the system.',
    icon_url: icon('LN'),
    trigger_rule: 'LOGIN',
    roleNames: ['system_admin', 'worker', 'resource_manager', 'travel_coordinator'],
  },
  {
    name: 'Consistent Access',
    description: 'Return often and keep your account active.',
    icon_url: icon('CA'),
    trigger_rule: 'LOGIN',
    roleNames: ['system_admin', 'worker', 'resource_manager', 'travel_coordinator'],
  },
  {
    name: 'Night Watch Ready',
    description: 'Stay present when the camp needs steady hands.',
    icon_url: icon('NW'),
    trigger_rule: 'LOGIN',
    roleNames: ['system_admin', 'worker', 'resource_manager', 'travel_coordinator'],
  },
  {
    name: 'Camp Manager Novice',
    description: 'Create your first camp without hesitation.',
    icon_url: icon('CM1'),
    trigger_rule: 'CAMP_CREATE',
    roleNames: ['system_admin'],
  },
  {
    name: 'Camp Manager Expert',
    description: 'Build multiple camps and keep the network growing.',
    icon_url: icon('CM2'),
    trigger_rule: 'CAMP_CREATE',
    roleNames: ['system_admin'],
  },
  {
    name: 'Multi Camp Manager',
    description: 'Coordinate several camps at once with confidence.',
    icon_url: icon('MCM'),
    trigger_rule: 'CAMP_CREATE',
    roleNames: ['system_admin'],
  },
  {
    name: 'Brave Returner',
    description: 'Bring a scouting team back safely.',
    icon_url: icon('BR'),
    trigger_rule: 'EXPEDITION_RETURN',
    roleNames: ['worker', 'travel_coordinator'],
  },
  {
    name: 'Brave Pathfinder',
    description: 'Lead a team through danger and return intact.',
    icon_url: icon('BP'),
    trigger_rule: 'EXPEDITION_RETURN',
    roleNames: ['worker', 'travel_coordinator'],
  },
  {
    name: 'Brave Expedition Captain',
    description: 'Guide repeated returns without losing momentum.',
    icon_url: icon('BEC'),
    trigger_rule: 'EXPEDITION_RETURN',
    roleNames: ['worker', 'travel_coordinator'],
  },
  {
    name: 'Diplomat Novice',
    description: 'Complete your first successful transfer.',
    icon_url: icon('DN'),
    trigger_rule: 'TRANSFER_COMPLETE',
    roleNames: ['system_admin', 'travel_coordinator'],
  },
  {
    name: 'Diplomat Keeper',
    description: 'Balance movement between camps with steady judgment.',
    icon_url: icon('DK'),
    trigger_rule: 'TRANSFER_COMPLETE',
    roleNames: ['system_admin', 'travel_coordinator'],
  },
  {
    name: 'Diplomat Master',
    description: 'Complete several transfers without disrupting operations.',
    icon_url: icon('DM'),
    trigger_rule: 'TRANSFER_COMPLETE',
    roleNames: ['system_admin', 'travel_coordinator'],
  },
  {
    name: 'Inventory Novice',
    description: 'Perform your first manual inventory adjustment.',
    icon_url: icon('IN'),
    trigger_rule: 'INVENTORY_ADJUST',
    roleNames: ['resource_manager', 'system_admin'],
  },
  {
    name: 'Inventory Keeper',
    description: 'Keep the ledger stable through repeated adjustments.',
    icon_url: icon('IK'),
    trigger_rule: 'INVENTORY_ADJUST',
    roleNames: ['resource_manager', 'system_admin'],
  },
  {
    name: 'Ledger Guardian',
    description: 'Protect the stock records from drift and confusion.',
    icon_url: icon('LG'),
    trigger_rule: 'INVENTORY_ADJUST',
    roleNames: ['resource_manager', 'system_admin'],
  },
  {
    name: 'Resource Scout',
    description: 'Bring back the first useful haul from the field.',
    icon_url: icon('RS'),
    trigger_rule: 'EXPEDITION_FOUND_RESOURCES',
    roleNames: ['worker', 'resource_manager', 'travel_coordinator'],
  },
  {
    name: 'Resource Finder',
    description: 'Collect enough supplies to matter for the camp.',
    icon_url: icon('RF'),
    trigger_rule: 'EXPEDITION_FOUND_RESOURCES',
    roleNames: ['worker', 'resource_manager', 'travel_coordinator'],
  },
  {
    name: 'Resource Hauler',
    description: 'Return with a haul that changes the stock outlook.',
    icon_url: icon('RH'),
    trigger_rule: 'EXPEDITION_FOUND_RESOURCES',
    roleNames: ['worker', 'resource_manager', 'travel_coordinator'],
  },
  {
    name: 'Healthy Routine',
    description: 'Keep the camp running with at least one healthy member.',
    icon_url: icon('HR'),
    trigger_rule: 'HEALTH_DAYS',
    roleNames: ['worker', 'resource_manager', 'travel_coordinator'],
  },
  {
    name: 'Healthy Shift',
    description: 'Maintain a stable health baseline across the camp.',
    icon_url: icon('HS'),
    trigger_rule: 'HEALTH_DAYS',
    roleNames: ['worker', 'resource_manager', 'travel_coordinator'],
  },
  {
    name: 'Healthy Watch',
    description: 'Keep conditions stable long enough to matter.',
    icon_url: icon('HW'),
    trigger_rule: 'HEALTH_DAYS',
    roleNames: ['worker', 'resource_manager', 'travel_coordinator'],
  },
  {
    name: 'Periodic Check Starter',
    description: 'Let the automated checks run successfully.',
    icon_url: icon('PCS'),
    trigger_rule: 'PERIODIC_CHECK',
    roleNames: ['system_admin', 'resource_manager'],
  },
  {
    name: 'Periodic Check Keeper',
    description: 'Keep the scheduled evaluations healthy and consistent.',
    icon_url: icon('PCK'),
    trigger_rule: 'PERIODIC_CHECK',
    roleNames: ['system_admin', 'resource_manager'],
  },
  {
    name: 'Periodic Check Master',
    description: 'Support long-running automated evaluations without failure.',
    icon_url: icon('PCM'),
    trigger_rule: 'PERIODIC_CHECK',
    roleNames: ['system_admin', 'resource_manager'],
  },
  {
    name: 'First Aid Route',
    description: 'Move medical support where it is needed most.',
    icon_url: icon('FAR'),
    trigger_rule: 'TRANSFER_COMPLETE',
    roleNames: ['travel_coordinator'],
  },
  {
    name: 'Supply Route',
    description: 'Complete a transfer that keeps camps supplied.',
    icon_url: icon('SR'),
    trigger_rule: 'TRANSFER_COMPLETE',
    roleNames: ['travel_coordinator'],
  },
  {
    name: 'Courier Command',
    description: 'Orchestrate more than one successful handoff.',
    icon_url: icon('CC'),
    trigger_rule: 'TRANSFER_COMPLETE',
    roleNames: ['travel_coordinator'],
  },
  {
    name: 'Login Specialist',
    description: 'Be available whenever the system needs attention.',
    icon_url: icon('LS'),
    trigger_rule: 'LOGIN',
    roleNames: ['system_admin'],
  },
  {
    name: 'Command Console',
    description: 'Access the system often enough to keep it under control.',
    icon_url: icon('CCS'),
    trigger_rule: 'LOGIN',
    roleNames: ['system_admin'],
  },
  {
    name: 'Control Room Presence',
    description: 'Stay connected and ready to act.',
    icon_url: icon('CRP'),
    trigger_rule: 'LOGIN',
    roleNames: ['system_admin'],
  },
  {
    name: 'Crisis Commander',
    description: 'Create a camp when the network needs another anchor.',
    icon_url: icon('CRC'),
    trigger_rule: 'CAMP_CREATE',
    roleNames: ['system_admin'],
  },
  {
    name: 'Shelter Architect',
    description: 'Expand the camp network with steady leadership.',
    icon_url: icon('SA'),
    trigger_rule: 'CAMP_CREATE',
    roleNames: ['system_admin'],
  },
  {
    name: 'Network Builder',
    description: 'Turn one camp into a coordinated set of shelters.',
    icon_url: icon('NB'),
    trigger_rule: 'CAMP_CREATE',
    roleNames: ['system_admin'],
  },
  {
    name: 'Field Support Brave',
    description: 'Return from the field with confidence and discipline.',
    icon_url: icon('FSB'),
    trigger_rule: 'EXPEDITION_RETURN',
    roleNames: ['worker'],
  },
  {
    name: 'Scout Brave',
    description: 'Lead a scouting route and bring everyone back.',
    icon_url: icon('SB'),
    trigger_rule: 'EXPEDITION_RETURN',
    roleNames: ['worker'],
  },
  {
    name: 'Camp Brave',
    description: 'Repeat successful returns until it becomes routine.',
    icon_url: icon('CB'),
    trigger_rule: 'EXPEDITION_RETURN',
    roleNames: ['worker'],
  },
  {
    name: 'Manual Tally Novice',
    description: 'Record the first manual inventory movement carefully.',
    icon_url: icon('MTN'),
    trigger_rule: 'INVENTORY_ADJUST',
    roleNames: ['resource_manager'],
  },
  {
    name: 'Manual Tally Keeper',
    description: 'Keep manual counts aligned with reality.',
    icon_url: icon('MTK'),
    trigger_rule: 'INVENTORY_ADJUST',
    roleNames: ['resource_manager'],
  },
  {
    name: 'Stock Sentinel',
    description: 'Defend the inventory from silent losses.',
    icon_url: icon('SS'),
    trigger_rule: 'INVENTORY_ADJUST',
    roleNames: ['resource_manager'],
  },
  {
    name: 'Supply Counter',
    description: 'Track enough adjustments to matter for planning.',
    icon_url: icon('SC'),
    trigger_rule: 'INVENTORY_ADJUST',
    roleNames: ['resource_manager'],
  },
  {
    name: 'Field Logistics',
    description: 'Bring back resources that support the frontline.',
    icon_url: icon('FL'),
    trigger_rule: 'EXPEDITION_FOUND_RESOURCES',
    roleNames: ['resource_manager'],
  },
  {
    name: 'Cache Builder',
    description: 'Turn field recovery into a reliable stock buffer.',
    icon_url: icon('CBU'),
    trigger_rule: 'EXPEDITION_FOUND_RESOURCES',
    roleNames: ['resource_manager'],
  },
  {
    name: 'Recovery Haul',
    description: 'Collect enough supplies to stabilize the camp.',
    icon_url: icon('RHA'),
    trigger_rule: 'EXPEDITION_FOUND_RESOURCES',
    roleNames: ['resource_manager'],
  },
  {
    name: 'Medical Watch',
    description: 'Keep the camp healthy enough for long-term planning.',
    icon_url: icon('MW'),
    trigger_rule: 'HEALTH_DAYS',
    roleNames: ['resource_manager'],
  },
  {
    name: 'Stable Ledger',
    description: 'Keep the system healthy through steady oversight.',
    icon_url: icon('SL'),
    trigger_rule: 'PERIODIC_CHECK',
    roleNames: ['resource_manager'],
  },
  {
    name: 'Operational Pulse',
    description: 'Support recurring checks without losing momentum.',
    icon_url: icon('OP'),
    trigger_rule: 'PERIODIC_CHECK',
    roleNames: ['resource_manager'],
  },
  {
    name: 'Rapid Route',
    description: 'Complete a transfer quickly and cleanly.',
    icon_url: icon('RR'),
    trigger_rule: 'TRANSFER_COMPLETE',
    roleNames: ['travel_coordinator'],
  },
  {
    name: 'Logistics Diplomat',
    description: 'Coordinate movement between camps without friction.',
    icon_url: icon('LD'),
    trigger_rule: 'TRANSFER_COMPLETE',
    roleNames: ['travel_coordinator'],
  },
  {
    name: 'Movement Master',
    description: 'Handle repeated transfers with confidence.',
    icon_url: icon('MM'),
    trigger_rule: 'TRANSFER_COMPLETE',
    roleNames: ['travel_coordinator'],
  },
  {
    name: 'Transit Guardian',
    description: 'Protect teams while they are away from camp.',
    icon_url: icon('TG'),
    trigger_rule: 'EXPEDITION_RETURN',
    roleNames: ['travel_coordinator'],
  },
  {
    name: 'Scout Channel',
    description: 'Route expeditions and keep them moving safely.',
    icon_url: icon('SCN'),
    trigger_rule: 'EXPEDITION_RETURN',
    roleNames: ['travel_coordinator'],
  },
  {
    name: 'Journey Captain',
    description: 'Lead several teams back without losing pace.',
    icon_url: icon('JC'),
    trigger_rule: 'EXPEDITION_RETURN',
    roleNames: ['travel_coordinator'],
  },
];
