-- MySQL Script generated by MySQL Workbench
-- jue 05 mar 2026 04:09:15 CST
-- Model: Sakila Full    Version: 2.0
-- MySQL Workbench Forward Engineering
--
-- ============================================================
-- CHANGELOG (parche v1.1 – mar 2026)
-- ============================================================
-- [1] persons           → ADD COLUMN `identification_code` VARCHAR(20) UNIQUE NULL
--                         (req. gestión humana #3: identificación auto-asignada por IA)
-- [2] admission_requests → ADD COLUMN `id_card_url` VARCHAR(500) NULL
--                         (req. gestión humana #2: imagen de tarjeta de identificación)
-- [3] camp_transfers    → ADD COLUMN `leader_person_id` INT UNSIGNED NULL
--                         (req. otros campamentos #2/#3: líder físico del traslado)
--                         ADD COLUMN `scheduled_delivery_date` DATETIME NULL
--                         (req. otros campamentos #3: agendar entrega/devolución de recursos)
-- ============================================================

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gestion_del_fin
-- -----------------------------------------------------


-- -----------------------------------------------------
-- Table `system_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system_config` (
  `id` TINYINT NOT NULL DEFAULT 1 COMMENT 'Always one, singleton row',
  `version` VARCHAR(20) NULL COMMENT 'e.g. "1.0.0"',
  `server_time` DATETIME NOT NULL COMMENT 'Central clock for all camps',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'General system parameters\n';


-- -----------------------------------------------------
-- Table `camps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camps` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Auto-increment PK',
  `name` VARCHAR(100) NOT NULL COMMENT 'Unique camp name',
  `location` VARCHAR(100) NULL,
  `status` ENUM('ACTIVE', 'ABANDONED') NOT NULL DEFAULT 'ACTIVE' COMMENT 'Current camp status. By default \'ACTIVE\'',
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Auto-increment PK',
  `name` VARCHAR(60) NOT NULL COMMENT 'e.g., system_admin | worker | resource_manager | travel_coordinator',
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
COMMENT = 'Roles that can be assigned to users';


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Auto-increment PK',
  `camp_id` INT UNSIGNED NOT NULL COMMENT 'FK to user\'s camp',
  `role_id` INT UNSIGNED NOT NULL,
  `username` VARCHAR(60) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL COMMENT 'bcrypt / argon2 hash',
  `is_active` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Users that have some sort of access to the system',
  `last_activity` TIMESTAMP NULL COMMENT 'Used to enforce the 20-min lock (jwt?)',
  `created_at` DATETIME NOT NULL DEFAULT NOW() COMMENT 'Default NOW()',
  PRIMARY KEY (`id`),
  INDEX `fk_users_camp_idx` (`camp_id` ASC),
  INDEX `fk_users_role_idx` (`role_id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  CONSTRAINT `fk_camp_id`
    FOREIGN KEY (`camp_id`)
    REFERENCES `camps` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Survivors';


-- -----------------------------------------------------
-- Table `professions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `professions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Auto-increment PK',
  `name` VARCHAR(80) NOT NULL COMMENT 'e.g., scout | farmer | guard | engineer | ...',
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `persons`
-- [CAMBIO #1] Se agrega `identification_code`:
--   El req. gestión humana #3 indica que al ingresar una persona
--   se le debe asignar automáticamente una identificación única.
--   Campo nullable porque se asigna DESPUÉS de la aprobación,
--   no al momento de crear el registro.
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `persons` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Auto-increment PK',
  `camp_id` INT UNSIGNED NOT NULL,
  `profession_id` INT UNSIGNED NOT NULL,
  `identification_code` VARCHAR(20) NULL COMMENT 'Auto-assigned unique ID after admission approval (e.g. SRV-00042)',
  `full_name` VARCHAR(150) NOT NULL,
  `age` TINYINT UNSIGNED NULL,
  `blood_type` VARCHAR(5) NULL COMMENT 'e.g., A+ | B+ | O+ | ...',
  `skills_summary` TEXT NULL COMMENT 'Text field',
  `photo_url` VARCHAR(500) NULL,
  `status` ENUM('SICK', 'HEALTHY', 'INJURED', 'AWAY', 'DEAD') NOT NULL DEFAULT 'HEALTHY' COMMENT 'Default \'HEALTHY\'',
  `admitted_at` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `identification_code_UNIQUE` (`identification_code` ASC),
  INDEX `fk_person_camp__id_idx` (`camp_id` ASC),
  INDEX `fk_persons_profession_id_idx` (`profession_id` ASC),
  CONSTRAINT `fk_persons_camp_id`
    FOREIGN KEY (`camp_id`)
    REFERENCES `camps` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persons_profession_id`
    FOREIGN KEY (`profession_id`)
    REFERENCES `professions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Also known as survivors';


-- -----------------------------------------------------
-- Table `admission_requests`
-- [CAMBIO #2] Se agrega `id_card_url`:
--   El req. gestión humana #2 indica que al registrar un nuevo
--   solicitante se debe poder adjuntar una imagen de tarjeta
--   de identificación, adicional a la foto del solicitante.
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admission_requests` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Auto-increment PK',
  `camp_id` INT UNSIGNED NOT NULL,
  `applicant_name` VARCHAR(150) NOT NULL,
  `applicant_age` TINYINT UNSIGNED NULL,
  `applicant_skills` TEXT NULL,
  `health_notes` TEXT NULL,
  `background_notes` TEXT NULL,
  `photo_url` VARCHAR(255) NULL,
  `id_card_url` VARCHAR(500) NULL COMMENT 'Optional image of applicant identification card (req. gestión humana #2)',
  `ai_decision` ENUM('ACCEPTED', 'PENDING', 'REJECTED') NOT NULL DEFAULT 'PENDING' COMMENT 'Output decision from AI',
  `ai_reasoning` TEXT NULL COMMENT 'Readable AI explaination based on the request\'s information',
  `ai_suggested_profession` VARCHAR(80) NULL COMMENT 'Profession name suggested by AI',
  `reviewed_by` INT UNSIGNED NULL COMMENT 'FK of reviewer (nullable until reviewd)',
  `final_decision` ENUM('ACCEPTED', 'REJECTED', 'PENDING') NOT NULL DEFAULT 'PENDING',
  `reviewed_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  INDEX `fk_admission_request_camp_idx` (`camp_id` ASC),
  INDEX `fk_user_reviewd_by_idx` (`reviewed_by` ASC),
  CONSTRAINT `fk_admission_requests_camp_id`
    FOREIGN KEY (`camp_id`)
    REFERENCES `camps` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reviewed_by`
    FOREIGN KEY (`reviewed_by`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `person_status_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `person_status_log` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Auto-increment PK',
  `person_id` INT UNSIGNED NOT NULL COMMENT 'FK to the person related to the logged status',
  `old_status` VARCHAR(20) NOT NULL,
  `new_status` VARCHAR(45) NOT NULL,
  `reason` TEXT NULL,
  `changed_by` INT UNSIGNED NOT NULL,
  `changed_at` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  INDEX `fk_person_id_idx` (`person_id` ASC),
  INDEX `fk_changed_by_idx` (`changed_by` ASC),
  CONSTRAINT `fk_person_status_log_person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_changed_by`
    FOREIGN KEY (`changed_by`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `profession_reassignment_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `profession_reassignment_log` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Auto-increment PK',
  `person_id` INT UNSIGNED NOT NULL,
  `from_profession_id` INT UNSIGNED NOT NULL,
  `to_profession_id` INT UNSIGNED NOT NULL,
  `reason` TEXT NULL,
  `start_date` DATE NOT NULL DEFAULT NOW(),
  `end_date` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_person_id_idx` (`person_id` ASC),
  INDEX `fk_from_profession_id_idx` (`from_profession_id` ASC),
  INDEX `fk_to_profession_id_idx` (`to_profession_id` ASC),
  CONSTRAINT `fk_reassignment_log_person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_from_profession_id`
    FOREIGN KEY (`from_profession_id`)
    REFERENCES `professions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_to_profession_id`
    FOREIGN KEY (`to_profession_id`)
    REFERENCES `professions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resource_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resource_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Auto-increment PK',
  `name` VARCHAR(80) NOT NULL COMMENT 'e.g., meat loaf | food | water | hygiene | medicine | ...',
  `unit` VARCHAR(20) NOT NULL COMMENT 'e.g., kg | liters | lb',
  `daily_ration` DECIMAL(8,2) UNSIGNED NOT NULL COMMENT 'Daily consumption per person',
  `minimum_stock` DECIMAL(10,2) UNSIGNED NOT NULL,
  `auto_daily` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Auto-increment PK',
  `camp_id` INT UNSIGNED NOT NULL,
  `resource_type_id` INT UNSIGNED NOT NULL,
  `quantity` DECIMAL(12,2) UNSIGNED NOT NULL DEFAULT 0.00 COMMENT 'Current total',
  `last_updated` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  INDEX `fk_camp_idx` (`camp_id` ASC),
  INDEX `fk_resource_type_idx` (`resource_type_id` ASC),
  UNIQUE INDEX `uq_camp_resource` (`camp_id` ASC, `resource_type_id` ASC),
  CONSTRAINT `fk_inventory_camp_id`
    FOREIGN KEY (`camp_id`)
    REFERENCES `camps` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventory_resource_type_id`
    FOREIGN KEY (`resource_type_id`)
    REFERENCES `resource_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory_log` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Auto-increment PK\n',
  `camp_id` INT UNSIGNED NOT NULL COMMENT 'Camp related to the log',
  `resource_type_id` INT UNSIGNED NOT NULL,
  `logged_by` INT UNSIGNED NULL COMMENT 'NULLABLE because of possible automated inventory logs',
  `log_type` ENUM('DAILY_GAIN', 'DAILY_RATION', 'MANUAL_IN', 'MANUAL_OUT', 'EXPEDITION_OUT', 'EXPEDITION_IN', 'TRANSFER_OUT', 'TRANSFER_IN') NOT NULL COMMENT 'e.g.: \'DAILY_GAIN\',\'DAILY_RATION\',\'MANUAL_IN\',\'MANUAL_OUT\',\'EXPEDITION_OUT\',\'EXPEDITION_IN\',\'TRANSFER_OUT\',\'TRANSFER_IN\'',
  `delta` DECIMAL(12,2) NOT NULL COMMENT '+ = stock in   − = stock out',
  `logged_at` DATETIME NOT NULL DEFAULT NOW(),
  `description` VARCHAR(255) NULL COMMENT 'Max 255 chars for reduced log descriptions',
  PRIMARY KEY (`id`),
  INDEX `fk_camp__id_idx` (`camp_id` ASC),
  INDEX `fk_resource_id_idx` (`resource_type_id` ASC),
  INDEX `fk_logged_by_idx` (`logged_by` ASC),
  CONSTRAINT `fk_inventory_log_camp_id`
    FOREIGN KEY (`camp_id`)
    REFERENCES `camps` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventory_log_resource_type_id`
    FOREIGN KEY (`resource_type_id`)
    REFERENCES `resource_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_logged_by`
    FOREIGN KEY (`logged_by`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contribution_overrides`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contribution_overrides` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Auto-increment PK',
  `person_id` INT UNSIGNED NOT NULL,
  `resource_type_id` INT UNSIGNED NOT NULL,
  `reason` VARCHAR(255) NOT NULL,
  `start_date` DATE NOT NULL DEFAULT NOW(),
  `end_date` DATE NULL,
  `created_by` INT UNSIGNED NOT NULL,
  `amount` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_person_id_idx` (`person_id` ASC),
  INDEX `fk_resource_type__id_idx` (`resource_type_id` ASC),
  INDEX `fk_created_by_idx` (`created_by` ASC),
  CONSTRAINT `fk_contribution_overrides_person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contribution_overrides_resource_type_id`
    FOREIGN KEY (`resource_type_id`)
    REFERENCES `resource_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_created_by`
    FOREIGN KEY (`created_by`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Overrides profession-defined contribution amounts';


-- -----------------------------------------------------
-- Table `expeditions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expeditions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Auto-increment PK',
  `camp_id` INT UNSIGNED NOT NULL,
  `destination` VARCHAR(255) NOT NULL,
  `status` ENUM('PLANNED', 'ONGOING', 'RETURNED', 'CANCELLED') NOT NULL DEFAULT 'PLANNED' COMMENT 'e.g.: \'PLANNED\',\'ONGOING\',\'RETURNED\',\'CANCELLED\'',
  `created_by` INT UNSIGNED NOT NULL,
  `departure_date` DATE NOT NULL,
  `expected_return_date` DATE NOT NULL COMMENT 'Expected but not actually max return date',
  `actual_return_date` DATE NULL,
  `max_return_date` DATE NOT NULL COMMENT 'Buffer from expected return date',
  `notes` TEXT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  INDEX `fk_camp_id_idx` (`camp_id` ASC),
  INDEX `fk_created_by_idx` (`created_by` ASC),
  CONSTRAINT `fk_expeditions_camp_id`
    FOREIGN KEY (`camp_id`)
    REFERENCES `camps` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_expeditions_created_by`
    FOREIGN KEY (`created_by`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `professions_resources_amounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `professions_resources_amounts` (
  `professions_id` INT UNSIGNED NOT NULL,
  `resource_type_id` INT UNSIGNED NOT NULL,
  `amount` DECIMAL(12,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`professions_id`, `resource_type_id`),
  INDEX `fk_resource_type_id_idx` (`resource_type_id` ASC),
  INDEX `fk_profession_type_id_idx` (`professions_id` ASC),
  CONSTRAINT `fk_prof_res_amounts_profession_id`
    FOREIGN KEY (`professions_id`)
    REFERENCES `professions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prof_res_amounts_resource_type_id`
    FOREIGN KEY (`resource_type_id`)
    REFERENCES `resource_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expedition_allocated_resources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expedition_allocated_resources` (
  `expedition_id` INT UNSIGNED NOT NULL,
  `resource_type_id` INT UNSIGNED NOT NULL,
  `amount` DECIMAL(12,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`expedition_id`, `resource_type_id`),
  INDEX `fk_resource_type_id_idx` (`resource_type_id` ASC),
  INDEX `fk_expedition_id_idx` (`expedition_id` ASC),
  CONSTRAINT `fk_exp_allocated_expedition_id`
    FOREIGN KEY (`expedition_id`)
    REFERENCES `expeditions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exp_allocated_resource_type_id`
    FOREIGN KEY (`resource_type_id`)
    REFERENCES `resource_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expedition_found_resources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expedition_found_resources` (
  `expedition_id` INT UNSIGNED NOT NULL,
  `resource_type_id` INT UNSIGNED NOT NULL,
  `amount` DECIMAL(12,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`expedition_id`, `resource_type_id`),
  INDEX `fk_resource_type_id_idx` (`resource_type_id` ASC),
  INDEX `fk_expedition_id_idx` (`expedition_id` ASC),
  CONSTRAINT `fk_exp_found_expedition_id`
    FOREIGN KEY (`expedition_id`)
    REFERENCES `expeditions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exp_found_resource_type_id`
    FOREIGN KEY (`resource_type_id`)
    REFERENCES `resource_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expedition_members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expedition_members` (
  `expedition_id` INT UNSIGNED NOT NULL,
  `person_id` INT UNSIGNED NOT NULL,
  INDEX `fk_expedition_id_idx` (`expedition_id` ASC),
  INDEX `fk_person_id_idx` (`person_id` ASC),
  PRIMARY KEY (`person_id`, `expedition_id`),
  CONSTRAINT `fk_exp_members_expedition_id`
    FOREIGN KEY (`expedition_id`)
    REFERENCES `expeditions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exp_members_person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camp_transfers`
-- [CAMBIO #3a] Se agrega `leader_person_id`:
--   El enunciado (otros campamentos #2 y #3) establece que cuando
--   se aprueba un traslado se debe designar a una persona que
--   físicamente lidere y transporte los recursos/personas hasta
--   el campamento destino. Es nullable porque se asigna al momento
--   de aprobar, no al crear la solicitud.
--   Referencia `persons` (no `users`) porque es el sobreviviente
--   físico que hace el viaje, no la cuenta del sistema.
--
-- [CAMBIO #3b] Se agrega `scheduled_delivery_date`:
--   El enunciado (otros campamentos #3) indica que el préstamo de
--   recursos entre campamentos debe agendarse para su entrega y
--   devolución. Este campo almacena la fecha/hora pactada.
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camp_transfers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Auto-increment PK',
  `requesting_camp` INT UNSIGNED NOT NULL,
  `target_camp` INT UNSIGNED NOT NULL,
  `status` ENUM('PENDING', 'APPROVED_SOURCE', 'APPROVED_TARGET', 'COMPLETED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
  `type` ENUM('RESOURCE', 'PERSON', 'MIXED') NOT NULL,
  `notes` TEXT NULL,
  `requested_by` INT UNSIGNED NOT NULL,
  `leader_person_id` INT UNSIGNED NULL COMMENT 'Physical leader who carries resources/people to destination camp (assigned on approval)',
  `scheduled_delivery_date` DATETIME NULL COMMENT 'Agreed date for resource delivery or return between camps (req. otros campamentos #3)',
  `approved_by_source` INT UNSIGNED NULL,
  `approved_by_target` INT UNSIGNED NULL,
  `approved_source_at` DATETIME NULL,
  `approved_target_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  INDEX `fk_requesting_camp_idx` (`requesting_camp` ASC),
  INDEX `fk_target_camp_idx` (`target_camp` ASC),
  INDEX `fk_requested_by_idx` (`requested_by` ASC),
  INDEX `fk_transfer_leader_person_idx` (`leader_person_id` ASC),
  INDEX `fk_approved_by_source_idx` (`approved_by_source` ASC),
  INDEX `fk_approved_by_target_idx` (`approved_by_target` ASC),
  CONSTRAINT `fk_requesting_camp`
    FOREIGN KEY (`requesting_camp`)
    REFERENCES `camps` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_target_camp`
    FOREIGN KEY (`target_camp`)
    REFERENCES `camps` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_requested_by`
    FOREIGN KEY (`requested_by`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transfer_leader_person`
    FOREIGN KEY (`leader_person_id`)
    REFERENCES `persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_approved_by_source`
    FOREIGN KEY (`approved_by_source`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_approved_by_target`
    FOREIGN KEY (`approved_by_target`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camp_transfer_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camp_transfer_item` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `camp_transfer_id` INT UNSIGNED NOT NULL,
  `item_type` ENUM('RESOURCE', 'PERSON') NOT NULL,
  `resource_type_id` INT UNSIGNED NULL COMMENT 'If NULL then its person item type',
  `person_id` INT UNSIGNED NULL COMMENT 'If null then its resource item type',
  `quantity` DECIMAL(10,2) UNSIGNED NULL COMMENT 'If NULL then is person item type',
  PRIMARY KEY (`id`),
  INDEX `fk_camp_transfer_id_idx` (`camp_transfer_id` ASC),
  INDEX `fk_resource_type_id_idx` (`resource_type_id` ASC),
  INDEX `fk_person_id_idx` (`person_id` ASC),
  CONSTRAINT `fk_camp_transfer_id`
    FOREIGN KEY (`camp_transfer_id`)
    REFERENCES `camp_transfers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transfer_item_resource_type_id`
    FOREIGN KEY (`resource_type_id`)
    REFERENCES `resource_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transfer_item_person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `achievements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `achievements` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Auto-increment PK.',
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NULL,
  `icon_url` VARCHAR(500) NOT NULL,
  `trigger_rule` VARCHAR(100) NOT NULL COMMENT 'e.g., first_expedition_returned',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_achievements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_achievements` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `achievement_id` INT UNSIGNED NOT NULL,
  `earned_at` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  INDEX `fk_user_id_idx` (`user_id` ASC),
  INDEX `fk_achivement_id_idx` (`achievement_id` ASC),
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_achivement_id`
    FOREIGN KEY (`achievement_id`)
    REFERENCES `achievements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;